easyrsa3/easyrsa
Changed the default encryption parameter for "easyrsa set-rsa-pass" and "easyrsa set-ec-pass" from "des3" to "aes256".
Solves second part of #58
=> changed default encrpytion algorithmus for keyfiles from des3 to aes256

doc/EasyRSA-Advanced.md, easyrsa3/vars.example
This PR is a continuation of PR#128. It adapts the documentation and examples to fit the code changes.
=> Update docs and examples to fit default PKI at $PWD/pki

easyrsa3/easyrsa
- "[[" syntax work only in "Bash"
=> Fix string comprehension

easyrsa3/easyrsa
Tested working on Windows, Linux and FreeBSD.
Fixes #230
=> Function to hide password input

easyrsa3/easyrsa
=> respect EASYRSA_SSL_CONF during init-pki

easyrsa3/vars.example
Improves 376c62f2b81e36db6f449ac7673013075b0c3ef1
=> update EASYRSA_CERT_EXPIRE new default value

easyrsa3/easyrsa
=> Add optional CRL reason parameter

op_test.sh
=> Add renew_cert() to op_test.sh

build/build-dist.sh
* Added --no-windows, --no-unix and no --no-compress to skip some
build steps.
* Use cp in a Linux and FreeBSD compatible way
* Set 'sed -i' backup extension (Linux and FreeBSD compatible)
(Linux regression from f0204c160b3cbdc041a91f2861febab24b7f5f76)
* Fix zip location to match tar (fixing also --bin-dest for win32)
* Align (y/n) with question in confirm
=> Multiple fix for build-dist.sh

.travis.yml
=> Travis: OSX SSL ver; Language: bash

easyrsa3/easyrsa
Also, always show SSL lib in use.
=> Use only verify_ssl_lib to call make_ssl_config

easyrsa3/easyrsa
Fix regression introduced by 6ecb6f489e0c0acd03b4f5b4559cdba7962077c3 in windows.
In fact, it is win32 mktemp bug.
=> Fix dirtemp windows

op_test.sh
=> Expand op_test: Inconsistent SAN behaviour

easyrsa3/easyrsa
=> Upgrade to 306: Create $EASYRSA_SSL_CONF if required

easyrsa3/easyrsa
=> Correct parameter to easyrsa_openssl in vars_setup

easyrsa3/easyrsa
Automate upgrading PKI from v2 to v307+
Automate upgrading CA from pre v306 to v307+
Info:
https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade
=> Easyrsa PKI upgrade

.gitignore, easyrsa3/easyrsa
=> Ignore serial.old

easyrsa3/easyrsa
=> Adds export-p8 command

doc/EasyRSA-Advanced.md
- The global options need to be set before the actual commands
- https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa#L219
=> Add a note in EasyRSA-Advanced.md

easyrsa3/easyrsa
fixed missing quotes leading to filename inconsistency in renew subcommand.
=> fixed renew filename confusion

doc/Intro-To-PKI.md
Just found a single letter typo
=> small typo fix

.github/workflows/action.yml, doc/EasyRSA-Readme.md
=> Re-arrange "# Signing a request" to fix markdown problem

easyrsa3/openssl-easyrsa.cnf
=> OpenSSL Configuration: Add required white space separator

wop_test.bat
Bug: Windows unit tests wipe out error in batch file
=> Windows unit test: On error then exit with error

easyrsa3/easyrsa
=> Add SSL Library version 2 to easyrsa_openssl()

easyrsa3/easyrsa
=> Add notice to 'init-pki': 'vars' file has now moved to PKI above

easyrsa3/easyrsa
Signed-off-by: Wharf in Ships Clothing <wiscii@protonmail.com>
=> Remove obsolete function copy_data_to_pki()

easyrsa3/easyrsa
=> Silence cleanup()

easyrsa3/easyrsa
=> Detect Windows and Git-for-Windows bash

easyrsa3/easyrsa
=> easyrsa_openssl() - Minor syle changes

easyrsa3/easyrsa
=> revoke(): Purge unquoted $opts + General improvements

ChangeLog, easyrsa3/easyrsa
=> Expand status reports to include checking a single certificate

easyrsa3/easyrsa
=> Correctly quote 'sed' and auto-escape ampersand

easyrsa3/easyrsa, easyrsa3/vars.example
This was not how I intended this PR to be presented but it is done now.
My sincere Apologies for any inconvenience.
`git log` will be correct.
Windows `date.exe` is also supported.
=> Replace cert dates

easyrsa3/easyrsa
=> Options: Check that $val is numeric when a number is expected

easyrsa3/easyrsa
=> sign-req: Enforce X509-type files exist and are used. (#581)

easyrsa3/easyrsa
Improve two comments and information() output
=> cleanup: Make "clean line" respect silent, batch and quiet modes

easyrsa3/easyrsa
=> detect_host: Use SSL Library version from EasyRSA version

easyrsa3/easyrsa
Plus a small tidy up.
Closes: #653
=> Options: Add '-s' to also enabe --silent mode.

easyrsa3/easyrsa
=> x509-types: Reset non-existent x509-types dir set by vars

easyrsa3/easyrsa
Signed-off-by: Ashutosh Ojha <ashutoshojha5@gmail.com>
=> fixed typo

easyrsa3/easyrsa
=> renew-req: Add command option 'nopass'

ChangeLog, easyrsa3/easyrsa
Phase-2: #684
Supersedes: #616
=> Remove renew-req

doc/EasyRSA-Renew-and-Revoke.md
Document the various EasyRSA version differences of renewal and revocation.
Closes: #626
Authors comment:
It has taken good luck, hard work and co-operation to save EasyRSA "renewal and revocation".
I am pleased to have provided the solution presented here.
=> Documentation: Add EasyRSA-Renew-and-Revoke.md

ChangeLog, easyrsa3/easyrsa
Closes: #696
Also, standardize similar error messages.
=> build-ca: Check x509-types 'ca' and 'COMMON' files exist

doc/EasyRSA-Renew-and-Revoke.md
=> Doc-Update: Note that all changes were included with Easy-RSA v3.1.1

ChangeLog
=> ChangeLog: Final update for v3.1.1

doc/EasyRSA-Contributing.md
=> Doc: EasyRSA-Contributing.md - Update

easyrsa3/easyrsa
=> Minor style change

easyrsa3/vars.example
=> vars.example: Add EASYRSA_NO_PASS and wrap long lines

easyrsa3/easyrsa
=> Use 'unset -v', consistently

easyrsa3/easyrsa
Make EasyRSA check for basic passphrase requirements.
=> build-ca: Improve passphrase input mechanism

ChangeLog, easyrsa3/easyrsa
=> Remove global options '--verbose' and '--quiet' as not required

easyrsa3/easyrsa
=> cleanup(): Exit with numeric error-code only

easyrsa3/easyrsa
=> Status Reports: Set 'LC_TIME=C.UTF-8', only used for reports

easyrsa3/easyrsa
=> Re-order output messages and subsequent newlines for aesthetics

easyrsa3/easyrsa
=> build_ca(): Wrap long lines

easyrsa3/easyrsa
=> Remove hard-coded unit-test password from build-ca

easyrsa3/easyrsa
=> build-ca: Minor code reformat (aesthetics)

easyrsa3/easyrsa
=> Move calling show_host() to function die(), where it belongs

easyrsa3/easyrsa
=> Remove ineffectual redirector

easyrsa3/easyrsa
=> Remove redundant separator lines

easyrsa3/easyrsa
=> Move verify_ssl_lib() - Always verify SSL lib, for all commands

ChangeLog, easyrsa3/easyrsa
Create default files for openssl-easyrsa.cnf, vars.example and x509-types files.
=> Automate support-file creation (Free packaging)

easyrsa3/easyrsa
=> Very minor changes to comments, help/msg text, wrap lines, code

easyrsa3/easyrsa
Allow default-san to find requests in pki/reqs folder.
=> Expand help to include undocumented commands

ChangeLog, easyrsa3/easyrsa
=> Revert "Completely Remove Upgrade Functionality"

easyrsa3/easyrsa
=> Revert "Expand help to include undocumented commands"

easyrsa3/easyrsa
Allow reuse of select_vars() by not also calling source_vars().
Minor improvement to error detection in source_vars().
=> Improve select_vars() and source_vars()

ChangeLog, easyrsa3/easyrsa
Make command `x509-eku` extensible. 
Allow `renew` to work for new EKU types.
=> Command: `x509-eku` `v2`

easyrsa3/easyrsa
=> Restore 128bit-random certificate serial-number

ChangeLog, README.md, dev/easyrsa-tools.lib, distro/windows/Licensing/LICENSE-OpenSSL.txt, distro/windows/Licensing/mksh-Win32.txt, doc/EasyRSA-Advanced.md, doc/EasyRSA-Contributing.md, doc/EasyRSA-Renew-and-Revoke.md, doc/Hacking.md, easyrsa3/easyrsa
Just thought I'd contribute some typo fixes that keep tripping up CI/CD checks in my projects. Nothing controversial, hopefully.
=> Fix minor typos

doc/EasyRSA-Renew-and-Revoke.md
Add available abbreviations for 'reason' codes.
Add 'renew' and 'expire/sign' details.
Add "_CA renewal_".
=> doc: Revoke and Renew, update for Easy-RSA v3.2.1

ChangeLog, dev/easyrsa-tools.lib, easyrsa3/easyrsa
The function of 'index.txt.attr' is to set SSL option "unique_subject = no". This function is handled by 'openssl-easyrsa.cnf' file.
=> Remove redundant file: index.txt.attr

easyrsa3/easyrsa
Move temp-file creation and $x509_type_file update to function.
=> add_critical_attrib_v2(): Move file access to function

ChangeLog, doc/EasyRSA-Advanced.md, easyrsa3/easyrsa
Also, add newline in EasyRSA-Advanced.md
=> Update Copyright 2025
